version: '3.1'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234